# Generated by Django 3.1.5 on 2021-01-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210128_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
